# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConverterWindow(object):
    def setupUi(self, ConverterWindow):
        ConverterWindow.setObjectName("ConverterWindow")
        ConverterWindow.resize(820, 252)
        self.centralwidget = QtWidgets.QWidget(ConverterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbLoadOldWord = QtWidgets.QPushButton(self.centralwidget)
        self.pbLoadOldWord.setMinimumSize(QtCore.QSize(150, 23))
        self.pbLoadOldWord.setMaximumSize(QtCore.QSize(150, 23))
        self.pbLoadOldWord.setObjectName("pbLoadOldWord")
        self.horizontalLayout.addWidget(self.pbLoadOldWord)
        self.chbxExportOld2Excel = QtWidgets.QCheckBox(self.centralwidget)
        self.chbxExportOld2Excel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chbxExportOld2Excel.setObjectName("chbxExportOld2Excel")
        self.horizontalLayout.addWidget(self.chbxExportOld2Excel)
        self.lblOldWord = QtWidgets.QLabel(self.centralwidget)
        self.lblOldWord.setObjectName("lblOldWord")
        self.horizontalLayout.addWidget(self.lblOldWord)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbLoadNewWord = QtWidgets.QPushButton(self.centralwidget)
        self.pbLoadNewWord.setMinimumSize(QtCore.QSize(150, 23))
        self.pbLoadNewWord.setMaximumSize(QtCore.QSize(150, 23))
        self.pbLoadNewWord.setObjectName("pbLoadNewWord")
        self.horizontalLayout_2.addWidget(self.pbLoadNewWord)
        self.chbxExportNew2Excel = QtWidgets.QCheckBox(self.centralwidget)
        self.chbxExportNew2Excel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.chbxExportNew2Excel.setObjectName("chbxExportNew2Excel")
        self.horizontalLayout_2.addWidget(self.chbxExportNew2Excel)
        self.lblNewWord = QtWidgets.QLabel(self.centralwidget)
        self.lblNewWord.setObjectName("lblNewWord")
        self.horizontalLayout_2.addWidget(self.lblNewWord)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pbCompareAndExport = QtWidgets.QPushButton(self.centralwidget)
        self.pbCompareAndExport.setMinimumSize(QtCore.QSize(150, 23))
        self.pbCompareAndExport.setMaximumSize(QtCore.QSize(150, 23))
        self.pbCompareAndExport.setObjectName("pbCompareAndExport")
        self.verticalLayout.addWidget(self.pbCompareAndExport)
        self.pbClean = QtWidgets.QPushButton(self.centralwidget)
        self.pbClean.setMinimumSize(QtCore.QSize(150, 23))
        self.pbClean.setMaximumSize(QtCore.QSize(150, 23))
        self.pbClean.setObjectName("pbClean")
        self.verticalLayout.addWidget(self.pbClean)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        ConverterWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConverterWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        ConverterWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConverterWindow)
        self.statusbar.setObjectName("statusbar")
        ConverterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConverterWindow)
        QtCore.QMetaObject.connectSlotsByName(ConverterWindow)

    def retranslateUi(self, ConverterWindow):
        _translate = QtCore.QCoreApplication.translate
        ConverterWindow.setWindowTitle(_translate("ConverterWindow", "VelesStroyApp"))
        self.pbLoadOldWord.setText(_translate("ConverterWindow", "LoadOldWord"))
        self.chbxExportOld2Excel.setText(_translate("ConverterWindow", "extract To Excel"))
        self.lblOldWord.setText(_translate("ConverterWindow", ":"))
        self.pbLoadNewWord.setText(_translate("ConverterWindow", "LoadNewWord"))
        self.chbxExportNew2Excel.setText(_translate("ConverterWindow", "extract To Excel"))
        self.lblNewWord.setText(_translate("ConverterWindow", ":"))
        self.pbCompareAndExport.setText(_translate("ConverterWindow", "CompareAndExport"))
        self.pbClean.setText(_translate("ConverterWindow", "Clean"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConverterWindow = QtWidgets.QMainWindow()
    ui = Ui_ConverterWindow()
    ui.setupUi(ConverterWindow)
    ConverterWindow.show()
    sys.exit(app.exec_())
